CREATE USER mitek WITH LOGIN PASSWORD 'onair';
CREATE DATABASE dbviz OWNER mitek;
\c dbviz

GRANT ALL PRIVILEGES ON SCHEMA public TO mitek;
ALTER DEFAULT PRIVILEGES FOR ROLE mitek IN SCHEMA public GRANT ALL ON TABLES TO mitek;
ALTER DEFAULT PRIVILEGES FOR ROLE mitek IN SCHEMA public GRANT ALL ON SEQUENCES TO mitek;

CREATE SCHEMA onair AUTHORIZATION mitek;
GRANT ALL PRIVILEGES ON SCHEMA onair TO mitek;
ALTER DEFAULT PRIVILEGES FOR ROLE mitek IN SCHEMA onair GRANT ALL ON TABLES TO mitek;
ALTER DEFAULT PRIVILEGES FOR ROLE mitek IN SCHEMA onair GRANT ALL ON SEQUENCES TO mitek;

ALTER USER mitek SET search_path TO onair, public;