apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: monitor-route
  namespace: monitor
spec:
  host: api.mydomain.com
  upstreams:
  - name: dashboard
    service: my-headlamp
    port: 80
  subroutes:
  - path: /headlamp
    action:
      pass: dashboard 

