apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: myapp-root-vs
spec:
  host: example.com
  tls:
    secret: myapp-tls     
    redirect:
      enable: true
  routes:
  - path: /
    action:
      redirect:
        url: https://api.example.com${request_uri}
        code: 301
